version: '3.8'

services:
  backend-node:
    build:
      args:
        - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-8000}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - nodejs-network

  jsdoc:
    image: node:20-alpine
    container_name: jsdoc-server
    ports:
      - "${DOCS_PORT:-8001}:${DOCS_PORT:-8001}"
    volumes:
      - .:/app
      - ./docs:/app/docs
    working_dir: /app
    command: >
      sh -c "
        npm install -g jsdoc http-server &&
        jsdoc src/**/*.js -d docs --configure jsdoc.conf.json 2>/dev/null || jsdoc src/**/*.js -d docs &&
        echo 'Documentation generated successfully' &&
        http-server docs -p ${DOCS_PORT:-8001} -a 0.0.0.0 --proxy http://${DOMAIN:-localhost}:${DOCS_PORT:-8001}?
      "
    restart: unless-stopped
    networks:
      - nodejs-network
    environment:
      - DOCS_PORT=${DOCS_PORT:-8001}

networks:
  nodejs-network:
    driver: bridge
