version: '3.8'

services:
  backend-node:
    build:
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - nodejs-network

  jsdoc:
    image: node:20-alpine
    container_name: jsdoc-server
    ports:
      - "${DOCS_PORT}:${DOCS_PORT}"
    volumes:
      - .:/app
      - ./docs:/app/docs
    working_dir: /app
    command: >
      sh -c "
        npm install -g jsdoc http-server &&
        jsdoc src/**/*.js -d docs --configure jsdoc.conf.json 2>/dev/null || jsdoc src/**/*.js -d docs &&
        echo 'Documentation generated successfully' &&
        http-server docs -p ${DOCS_PORT} -a 0.0.0.0 --proxy http://localhost:${DOCS_PORT}?
      "
    restart: unless-stopped
    networks:
      - nodejs-network
    environment:
      - DOCS_PORT=${DOCS_PORT}

networks:
  nodejs-network:
    driver: bridge
