version: '3.8'

services:
  backend-node:
    build:
      args:
        - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8000}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
