version: '3.8'

services:
  backend-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8000}
    container_name: backend-node-prod
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nodejs-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-8000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  nodejs-network:
    driver: bridge
